---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sshguard::default]
    attributes: {
     "sshguard": {
     	"whitelistips": ["1.2.3.4", "5.6.7.8"]
     	},
 }
  - name: nofw
    run_list:
      - recipe[sshguard::default]
    attributes: {
      "sshguard":{
      	"whitelistips":["1.2.3.4", "5.6.7.8"],
        "initfirewall":"true"
      },
    }
